title: Footer
blueprint: footer
data:
  description: 'At Voyager, we are broadband and communication specialists. Proudly New Zealand owned, we keep Kiwis online at home and at work with our supersonic broadband speeds.'
  solutions_menu: solutions
  about_menu: about
  copyright_text: 'Voyager Wholesale'
  privacy_link: /privacy
  terms_link: /terms
