title: 'Social Media'
blueprint: social_media
data:
  social_links:
    -
      id: rAI3nWKC
      type: social
      enabled: true
      platform: facebook
      url: 'https://www.facebook.com/voyagernz'
    -
      id: qCL4wqop
      type: social
      enabled: true
      platform: instagram
      url: 'https://www.instagram.com/voyagernz/'
    -
      id: mkRb2eR1
      type: social
      enabled: true
      platform: twitter
      url: 'https://x.com/voyagernz'
    -
      id: SdZis10i
      type: social
      enabled: true
      platform: linkedin
      url: 'https://www.linkedin.com/company/voyager-internet-ltd'
